public inherited sharing class KeycloakConstants {
    public static final String SERVICE_NAME_GATEWAY_SERVICE = 'GatewayService';
    public static final String HDID_PLACEHOLDER = '{HDID}';
    public static final String TEST_ENDPOINT = 'https://test.com/{HDID}';
    public static final String CALLOUT_TYPE_GET = 'GET';
    public static final String CALLOUT_TYPE_POST = 'POST';
    public static final String CALLOUT_TYPE_PUT = 'PUT';
    public static final String CALLOUT_TYPE_DELETE = 'DELETE';
    public static final String HG_SALESFORCE = 'Salesforce';
    public static final String TEST_HDID_RESPONSE = '{"resourcePayload": {"betaFeatures": ["Salesforce"]}}';
}